version: 2
updates:
  # Flutter/Dart dependencies for Android app
  - package-ecosystem: "pub"
    directory: "/einsteini-android"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "flutter"
    commit-message:
      prefix: "deps(flutter)"
      include: "scope"

  # Node.js dependencies for backend
  - package-ecosystem: "npm"
    directory: "/einsteini-backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "deps(backend)"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Node.js dependencies for dashboard
  - package-ecosystem: "npm"
    directory: "/einsteini-dashboard"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "dashboard"
    commit-message:
      prefix: "deps(dashboard)"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Node.js dependencies for extension
  - package-ecosystem: "npm"
    directory: "/einsteini-extension"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "extension"
    commit-message:
      prefix: "deps(extension)"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/einsteini-backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "deps(docker)"

  - package-ecosystem: "docker"
    directory: "/einsteini-dashboard"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "deps(docker)"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(actions)"
